update action to include check for large images

diff --git a/.github/workflows/quarto-publish.yml b/.github/workflows/quarto-publish.yml
--- a/.github/workflows/quarto-publish.yml
+++ b/.github/workflows/quarto-publish.yml
@@ -4,7 +4,6 @@ on:
   push:
     branches:
       - main
-      - ethiopia-course
   pull_request:
 
 jobs:
@@ -15,6 +14,17 @@ jobs:
     steps:
       - name: Check out repository
         uses: actions/checkout@v3
+
+      - name: Check for large images (>500 KB)
+        run: |
+          echo "Checking for large images (>500 KB)…"
+          files=$(find . -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) -size +500k)
+          if [ -n "$files" ]; then
+            echo "::error::Large images detected (>500 KB). Please optimise images before committing. See https://blog.bioconductor.org/contributing.html"
+
+            echo "$files"
+            exit 1
+          fi
 
       - name: Set up Quarto
         uses: quarto-dev/quarto-actions/setup@v2
